version: '3.7'

volumes:
  pg_data:
services:
  db:
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: 6512
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    volumes:
      - pg_data:/var/lib/postgresql/data/

  pares:
    build: ./
    restart: always
    command: >
      bash -c "alembic upgrade head && python bot.py"
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  redis:
    image: 'bitnami/redis:latest'
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes


  celery_worker:
    build: ./
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - pares
      - redis
    command: >
      bash -c "celery -A celery_conf worker -l INFO"
    links:
      - redis

  celery_beat:
    build: ./
    restart: always
    volumes:
      - ./:/app
    depends_on:
      - pares
      - redis
      - celery_worker
    command: >
      bash -c "celery -A celery_conf beat -l INFO"
    links:
      - redis