version: "3.7"

services:
  celery_worker:
    build: app/celery_conf/
    restart: always
    volumes:
      - .:/app
    depends_on:
      - redis
      - pares

  pares:
    build: ./
    restart: always
    depends_on:
      - postgresql
    volumes:
      - .:/usr/src/app/


  postgresql:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/


  redis:
    image: redis
    restart: always

volumes:
  postgres_data: