"""added review count models

Revision ID: 097b041333a4
Revises: 36c56c2761c4
Create Date: 2022-08-09 04:05:35.921150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097b041333a4'
down_revision = '36c56c2761c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('double_gis_review_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flamp_review_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviews_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flamp_review_count')
    op.drop_table('double_gis_review_count')
    # ### end Alembic commands ###
