"""fix

Revision ID: 36c56c2761c4
Revises: f65db0deb859
Create Date: 2022-08-08 16:58:52.764268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c56c2761c4'
down_revision = 'f65db0deb859'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
