"""added review count models

Revision ID: 60b62c5c0349
Revises: 9c309c69d78d
Create Date: 2022-08-09 04:24:25.185969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60b62c5c0349'
down_revision = '9c309c69d78d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('double_gis_review_count', sa.Column('place_id', sa.String(), nullable=False))
    op.add_column('flamp_review_count', sa.Column('place_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flamp_review_count', 'place_id')
    op.drop_column('double_gis_review_count', 'place_id')
    # ### end Alembic commands ###
