"""added field website to review model

Revision ID: 75872bb2d20d
Revises: 8e27c544d6c1
Create Date: 2022-08-10 04:14:15.923554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75872bb2d20d'
down_revision = '8e27c544d6c1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('website', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'website')
    # ### end Alembic commands ###
