"""fix reviews count models

Revision ID: 9c309c69d78d
Revises: 097b041333a4
Create Date: 2022-08-09 04:23:02.103540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c309c69d78d'
down_revision = '097b041333a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
