"""fix3

Revision ID: ec46b1e36eb6
Revises: 60b62c5c0349
Create Date: 2022-08-09 04:38:39.179316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec46b1e36eb6'
down_revision = '60b62c5c0349'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('double_gis_review_count', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=42, cycle=True),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('flamp_review_count', 'id',
               existing_type=sa.INTEGER(),
               server_default=sa.Identity(always=False, start=42, cycle=True),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flamp_review_count', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('double_gis_review_count', 'id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###
